Repository MHKiT-Software/MHKiT-Python, pull requests merged in 2022-11, with the labels that each got.

#194 Fix pip install tests
  .github/workflows/.coveragehindcastrc
  .github/workflows/.coveragerc
  .github/workflows/main.yml
  .github/workflows/pytest-hindcast.ini
  .github/workflows/pytest.ini
  .pypirc
  mhkit/tests/wave/io/test_hindcast.py
  requirements.txt
  setup.py
Labels: Clean Up

#193 Add function to compute value at a given return period
  examples/extreme_response_full_sea_state_example.ipynb
  mhkit/loads/extreme.py
  mhkit/tests/loads/test_loads.py
Labels: enhancement, wave module

#186 Dolfyn general updates
  examples/adcp_example.ipynb
  examples/adv_example.ipynb
  examples/data/dolfyn/test_data/BenchFile01_func.nc
  examples/data/dolfyn/test_data/RDI_withBT.nc
  examples/data/dolfyn/test_data/VelEchoBT01.nc
  examples/data/dolfyn/test_data/VelEchoBT01_rotate_beam2inst.nc
  examples/data/dolfyn/test_data/vector_data01_GN.nc
  examples/data/dolfyn/test_data/vector_data01_avg.nc
  examples/data/dolfyn/test_data/vector_data01_bin.nc
  examples/data/dolfyn/test_data/vector_data01_func.nc
  examples/data/dolfyn/test_data/vector_data01_func_demean.nc
  examples/data/dolfyn/test_data/vector_data01_funcdif.nc
  examples/data/dolfyn/test_data/winriver01.nc
  examples/data/dolfyn/test_data/winriver02.nc
  examples/data/dolfyn/test_data/winriver02_rotate_ship2earth.nc
  mhkit/dolfyn/adp/clean.py
  mhkit/dolfyn/adv/clean.py
  mhkit/dolfyn/adv/turbulence.py
  mhkit/dolfyn/binned.py
  mhkit/dolfyn/io/api.py
  mhkit/dolfyn/io/base.py
  mhkit/dolfyn/io/nortek.py
  mhkit/dolfyn/time.py
  mhkit/dolfyn/tools/fft.py
  mhkit/dolfyn/tools/misc.py
  mhkit/dolfyn/velocity.py
  mhkit/tests/dolfyn/test_analysis.py
  mhkit/tests/dolfyn/test_clean.py
  mhkit/tests/dolfyn/test_read_io.py
  mhkit/tests/dolfyn/test_tools.py
  requirements.txt
  setup.py
Labels: Clean Up, dolfyn module

#197 Directional NDBC
  examples/directional_waves.ipynb
  examples/environmental_contours_example.ipynb
  mhkit/tests/wave/io/test_ndbc.py
  mhkit/wave/graphics.py
  mhkit/wave/io/ndbc.py
Labels: enhancement
