Repository MHKiT-Software/MHKiT-Python, pull requests merged in 2024-12, with the labels that each got.

#365 FIx Flow Duration Curve Plot Bug
  mhkit/river/graphics.py
Labels: bug

#360 Fix warnings in the documentation build
  examples/ADCP_Delft3D_TRTS_example.ipynb
  examples/PacWave_resource_characterization_example.ipynb
  examples/SWAN_example.ipynb
  examples/data/river/ADCP_transect/TRTS_transect_map.png
  examples/data/strain/blade_hub_interface.png
  examples/data/strain/global_cs.png
  examples/data/strain/loading_setup.png
  examples/data/strain/local_cs_full.png
  examples/data/strain/rotation.png
  examples/strain_measurement_example.ipynb
  mhkit/acoustics/__init__.py
  mhkit/acoustics/analysis.py
  mhkit/acoustics/graphics.py
  mhkit/acoustics/io.py
  mhkit/mooring/graphics.py
  mhkit/power/quality.py
  mhkit/tests/wave/io/test_swan.py
  mhkit/tidal/graphics.py
  mhkit/wave/graphics.py
  mhkit/wave/io/ndbc.py
  mhkit/wave/io/swan.py
Labels: Clean Up

#363 __init__ Version 0.9.0
  README.md
  mhkit/__init__.py
Labels: documentation

#362 Fix Mac OS Tests
  mhkit/tests/dolfyn/test_motion.py
Labels: Clean Up

#367 Use `main` as Primary Branch
  .github/workflows/main.yml
  .github/workflows/pypi.yml
  README.md
  examples/qc_example.ipynb
  examples/river_example.ipynb
  examples/tidal_example.ipynb
Labels: Clean Up

#361 MHKiT 0.9.0
  .github/workflows/main.yml
  .github/workflows/pypi.yml
  README.md
  examples/qc_example.ipynb
  examples/river_example.ipynb
  examples/tidal_example.ipynb
Labels: release
